<?xml version="1.0"?>
<package format="3">
  <name>oscp_imu_ros2</name>
  <version>0.0.1</version>
  <description>ROS2 wrapper for OSCP IMU driver</description>

  <maintainer email="rayan@oscp.com">you</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Core ROS deps -->
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>

  <!-- Threading -->
  <depend>libstdcxx</depend>

  <!-- Custom messages -->
  <depend>oscp_msgs</depend>
  <depend>oscp_libraries</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>